name: Oil & Rope Theme CI

on:
  [push]

jobs:
  test-and-build:
    name: Test and build
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: '[PROD] Install dependencies and build'
        env:
          NODE_ENV: production
        run: |
          npm ci
          npm run build
          rm -rf node_modules/

      - name: '[DEV] Install dependencies'
        run: |
          npm ci

      - name: Linter
        run: |
          npm run lint

      - name: Test
        run: |
          npm test

      - name: Update coverage
        if: ${{ matrix.node-version == '18.x' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false # CI can continue without Codecov
          verbose: true

  build-and-push:
    name: Build Image and Push
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Since the format `developmentType/Code` is invalid we need to replace it
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]${{ github.ref_name }}" | sed -e 's/\//-/g'
        id: extra_branch_name

      - name: Build & Push Image
        if: ${{ success() }}
        uses: docker/build-push-action@v3
        env:
          DOCKERFILE: docker/Dockerfile
          TAG: ${{ steps.extra_branch_name.outputs.branch == 'master' && 'latest' || steps.extra_branch_name.outputs.branch }}
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/theme:${{ env.TAG }}
          file: ${{ env.DOCKERFILE }}
