name: Oil & Rope Theme CI

on:
  [push]

jobs:
  node-build:
    name: Node Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18]

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Check syntax
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Tests
        run: npm test

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]${{ github.ref_name }}" | sed -e 's/\//-/g'
        id: extra_branch_name

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        if: ${{ success() }}
        uses: docker/build-push-action@v3
        env:
          DOCKERFILE: docker/Dockerfile
          TAG: ${{ steps.extra_branch_name.outputs.branch == 'master' && 'latest' || steps.extra_branch_name.outputs.branch }}
        with:
          push: true
          tags: oilandrope/theme:${{ env.TAG }}
          file: ${{ env.DOCKERFILE }}
