name: Node checker

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  node-build:
    name: Node Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Check syntax
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Tests
        run: npm test

      - name: Updating Codecov (coverage)
        if: ${{ success() }}
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./coverage/clover.xml
